### ISSUE TITLE
Multiselect can't show after hot restart

### ISSUE THREAD

**Issue by ezaatama** [CodeFoxLk/flutter_multi_select#1]
Hello, i have trouble with this package. After hot restart application my multiselect can't show and this trouble always repeat. Any solutions?

**Comment by CodeFoxLk** [comment]
Can you share the full code, please? Are you facing this behavior in the example project too?

**Comment by ezaatama** [comment]
solved problem sir, I'm sorry I forgot to use futurebuilder when I took the API response
