### ISSUE TITLE
A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.

### ISSUE THREAD

**Issue by Mahrash-Malik** [CodeFoxLk/flutter_multi_select#2]
Hi, when i use  this package, it give me this error during complie time.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

I found the solution which works for me kindly check the attachment.

![image](https://user-images.githubusercontent.com/59029044/145385999-81e57e1e-8480-46c2-b817-1ff979f2c1e1.png)

**Comment by CodeFoxLk** [comment]
Thanks for your information. This issue comes with the flutter v.2.8.0. I have released flutter_multi_select_items v.0.2.0 with this bug fix.
