### ISSUE TITLE
[Feature_Recommendation] Add a field to add a Selected Items List for Preselected Options

### ISSUE THREAD

**Issue by vaidikkamde** [CodeFoxLk/flutter_multi_select#4]
Can we add a parameter which takes a list of Preselected values and match them with the values and have them Selected by default when the user opens the multi_select checkbox list or chips.

**Comment by CodeFoxLk** [comment]
you can use a controller to get all selected items and, selected = true of MultiSelectCard or CheckListCard for making them selected in initializing.


check this - > flutter_multi_select/example/lib/widgets/multiselect_features/controller_example.dart
