### ISSUE TITLE
MultiSelectCard’s selected IS NOT WORK

### ISSUE THREAD

**Issue by TEENSTITANS** [CodeFoxLk/flutter_multi_select#9]
i set THE selected is true, code like this, but it not work!

`        items.add(MultiSelectCard(
          value: itemData,
          label: ‘All’，
          enabled: true,
          selected: true,
        ));
`

**Comment by CodeFoxLk** [comment]
could you check the newest version? [0.4.2](https://pub.dev/packages/flutter_multi_select_items/versions/0.4.2)

**Comment by TEENSTITANS** [comment]
@CodeFoxLk 

Thank you for your reply, I'm sorry for just getting back to you, I found out that it was my problem, my data existed inside the database, so the default selected data was not loading after initialization, but the problem has been solved now, thanks for the library you provided on pub.
